#!/bin/bash

usage() { echo "Usage: $0 -m \"MESSAGE\" -p \$(pwd)" 1>&2; exit 1; }

if [ $# -lt 4 ]; then
  usage
  exit 2
fi

while getopts ":m:p:" o; do
    case "${o}" in
        m)
            message=${OPTARG}
            ;;
        p)
            path=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

cd $path
[[ $? -ne 0 ]] && echo "Path doesn't exist" && exit 3

git add --all :/&& git commit -m"$message" && git push
